# Generated by Django 4.2.4 on 2023-09-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0002_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='history',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
