# Generated by Django 4.2.4 on 2023-09-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0003_comment_title_history_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
