# Generated by Django 4.2.4 on 2023-09-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0005_comment_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='n_images',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='modified_at',
            field=models.DateTimeField(),
        ),
    ]
