# Generated by Django 4.2.4 on 2023-09-12 12:40

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('histories', '0006_history_n_images_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'description')},
        ),
    ]
