# Generated by Django 4.2.4 on 2023-09-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0007_alter_comment_options_alter_comment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Imagen'),
        ),
    ]
