# Generated by Django 4.2.4 on 2023-09-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0008_alter_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='permit_level',
            field=models.CharField(default='r', max_length=1, verbose_name='Permitir'),
        ),
    ]
